version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: userpassword
    restart: always
    ports:
      - '3306:3306'
    hostname: mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    restart: always
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 2
        NODE_VERSION: "lts/*"
    command: sleep infinity
    ports:
      - '5000:5000'
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/workspace
